spring.application.name=FlightReservationApplication

spring.datasource.url=jdbc:mysql://terraform-20260305055535911100000007.csv6y8s8akse.us-east-1.rds.amazonaws.com:3306/flightdb?createDatabaseIfNotExist=true
spring.datasource.username=admin
spring.datasource.password=Redhat123
frontend.url=http://3.85.30.65:80


# Hibernate properties for MySQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.auto-commit=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
server.address=0.0.0.0
